FROM alpine:3.10
RUN apk update \
    && apk add --virtual build-dependencies \
        build-base

RUN apk add \
  "bash" \
  "openssl"

ENV LANG en_GB.UTF-8
ENV LANGUAGE en_GB:en
ENV LC_ALL en_GB.UTF-8

COPY ./migrate.prod.sh /root/migrate.sh
COPY ./_build/prod/rel /app

WORKDIR /app
CMD ./pr/bin/pr start
