# fly.toml file generated for sonosnow on 2022-05-07T16:42:17+01:00

app = "sonosnow"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "8080"
  REDIRECT_URL_BASE = "https://sonosnow.fly.dev"
  HOSTNAME = "sonosnow.fly.dev"
  # Set feature flags in secrets now they override this
  # These wont be applied from a CI deploy, that requires a local CLI deploy
  FF_VOLUME = "true"
  FF_TOGGLE_PLAYBACK = "true"
  FF_SKIP = "true"
  RELEASE_COOKIE = "sonosnow"

[build]
  image = "ghcr.io/errkk/playrequest/pr:latest"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

# [deploy]
#   release_command = "bin/pr eval 'PR.ReleaseTasks.migrate'"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
